name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v3.5.2

    - name: Build
      run: |
        make -j2
    
    - name: Upload  Build Artifacts
      uses: actions/upload-artifact@v4.5.0
